### ISSUE TITLE
Doesn't seem to be compatible with newer versions of node

### ISSUE THREAD

**Issue by semanticart** [creationix/postgres-js#2]
Trying to run the example, I get:

```
Error: No longer accepting filename extension in module names
    at findModulePath (node.js:437:11)
    at loadModule (node.js:555:22)
    at require (node.js:683:12)
    at Object.<anonymous> (/Users/xxx/src/postgres-js/server.js:2:16)
    at Module._compile (node.js:704:23)
    at node.js:732:20
    at fs:51:23
    at node.js:813:9
```

trying without the .js extension in the postgres require, I get

```
Error: Cannot find module 'postgres'
    at loadModule (node.js:557:15)
    at require (node.js:683:12)
    at Object.<anonymous> (/Users/xxx/src/postgres-js/server.js:2:16)
    at Module._compile (node.js:704:23)
    at node.js:732:20
    at fs:51:23
    at node.js:813:9
```

**Comment by creationix** [comment]
Yes, this module is deprecated, I have a newer version that's running today as part of the sousaball game.

http://github.com/creationix/sousaball/blob/master/lib/postgres-pure.js
Note that is needs the md5 library and buffer-extras library as dependencies.

**Comment by semanticart** [comment]
awesome, thank you

**Comment by creationix** [comment]
Closing.
